export const TOPSPEED_BUTTON_SELECT = 'TOPSPEED_BUTTON_SELECT'
export const WEIGHT_CAPACITY_BUTTON_SELECT = 'WEIGHT_CAPACITY_BUTTON_SELECT'
export const SORT_BY_SPEED = 'SORT_BY_SPEED'
export const SORT_BY_MAKE = 'SORT_BY_MAKE'